In [4]:
import numpy as np
import random

In [16]:
x = np.arange(0,100,1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.random.shuffle(x)
x

array([87, 73, 85, 95, 32, 67, 31, 42, 62, 70,  6,  1, 16,  2,  0, 83, 33,
       56, 98, 77, 14, 65, 66, 43, 71, 91, 30, 11, 48, 97, 72, 15, 17, 80,
       21, 96, 12, 89, 19, 37, 40, 45, 57,  9, 20, 59, 39,  3, 64,  8, 46,
       25, 29,  7, 51, 84, 74, 23, 61, 99, 94, 34, 58, 55, 44, 69,  4, 53,
       93, 28, 10, 60, 49, 26, 88, 75, 92, 24, 27, 79,  5, 81, 50, 52, 18,
       13, 86, 22, 63, 76, 41, 82, 68, 38, 35, 47, 90, 54, 36, 78])

In [14]:
id = random.sample(list(x),100)
id

[21,
 89,
 11,
 14,
 90,
 78,
 55,
 23,
 64,
 75,
 96,
 26,
 40,
 86,
 57,
 61,
 93,
 97,
 70,
 92,
 16,
 34,
 65,
 18,
 51,
 9,
 45,
 36,
 62,
 67,
 38,
 43,
 31,
 71,
 80,
 66,
 6,
 50,
 99,
 52,
 77,
 29,
 60,
 69,
 91,
 4,
 3,
 63,
 15,
 94,
 49,
 19,
 28,
 12,
 39,
 83,
 41,
 10,
 54,
 32,
 56,
 82,
 44,
 73,
 87,
 27,
 1,
 74,
 84,
 88,
 85,
 17,
 7,
 59,
 25,
 37,
 95,
 58,
 22,
 81,
 79,
 46,
 0,
 72,
 98,
 5,
 20,
 47,
 8,
 68,
 76,
 2,
 30,
 33,
 48,
 35,
 42,
 53,
 13,
 24]

In [15]:
x[id]

array([21, 89, 11, 14, 90, 78, 55, 23, 64, 75, 96, 26, 40, 86, 57, 61, 93,
       97, 70, 92, 16, 34, 65, 18, 51,  9, 45, 36, 62, 67, 38, 43, 31, 71,
       80, 66,  6, 50, 99, 52, 77, 29, 60, 69, 91,  4,  3, 63, 15, 94, 49,
       19, 28, 12, 39, 83, 41, 10, 54, 32, 56, 82, 44, 73, 87, 27,  1, 74,
       84, 88, 85, 17,  7, 59, 25, 37, 95, 58, 22, 81, 79, 46,  0, 72, 98,
        5, 20, 47,  8, 68, 76,  2, 30, 33, 48, 35, 42, 53, 13, 24])